### ISSUE TITLE
A question about function 'constr()'

### ISSUE THREAD

**Issue by MaxLingwei** [peiyunh/tiny#1]
Hello, Peiyun Hu.
I've read your paper. And I downloaded the code for testing. But I met a problem when I run minimal_demo.m as follow:
```
>> minimal_demo
Undefined function or variable 'dagnn.Split'.

Error in dagnn.DagNN.loadobj (line 27)
      block = constr() ;

Error in minimal_demo (line 31)
net = dagnn.DagNN.loadobj(net.net);
```
I think I've installed matconvnet successfully since vl_testnn works well. And I've search on Google about constr() but found nothing to do. So would you give me some suggestion about this problem?
Thank you very much!

**Comment by flamerr** [comment]
>> minimal_demo
Undefined function or variable 'dagnn.Split'.

Error in dagnn.DagNN.loadobj (line 27)
      block = constr() ;

Error in minimal_demo (line 31)
net = dagnn.DagNN.loadobj(net.net);
same error...

**Comment by peiyunh** [comment]
`Split` operation is implemented in [my fork of Matconvnet](https://github.com/peiyunh/matconvnet/blob/9822ec97f35cf5a56ae22707cc1c04e0d738e7db/matlab/%2Bdagnn/Split.m).

**Comment by MaxLingwei** [comment]
@peiyunh Thank you very much! Your work is so great that helps me a lot!

**Comment by johanna-codes** [comment]
I have the same problem. I'm using Windows 7. Matlab 2015b. I think MatConvNet  is correctly installed (I followed the instructions) . I have the folder \matconvnet-master\matlab\+dagnn and I saved the file Split.m inside it. Didn't work.
