### ISSUE TITLE
Training hr_res101('train') error

### ISSUE THREAD

**Issue by niamul070** [peiyunh/tiny#17]
Hello I am trying to train hr_res101('train') with Wider face data. I compiled a CPU only version with matlab 2016b and matconvnet in ubuntu 14.04. After running the hr_res101('train') script I am getting the following error. 

Trying to initialize the structure of resnet-101-simple
Unknown model: cannot initialize.
Loading pretrained weights from models/imagenet-resnet-101-dag.mat
Loaded imdb from data/widerface/imdb.mat
cluster path: data/widerface/RefBox_N25_scaled.mat
Undefined variable "dagnn" or class "dagnn.Split".

Error in cnn_add_loss_fcn8s_resnet101_simple (line 120)
net.addLayer('split', dagnn.Split('childIds', {1:N, N+1:5*N}), ...

Error in cnn_widerface (line 181)
    net = cnn_add_loss_fcn8s_resnet101_simple(opts, net);

Error in hr_res101 (line 41)
    cnn_widerface('inputSize', inputSize, ...

**Comment by peiyunh** [comment]
Hi, it seems you are missing the Split.m, which can be found in my fork of MatConvNet. Please find it [here](https://github.com/peiyunh/matconvnet/blob/cf638ce2e09cc87bf4549200761b1c4c01a31a8e/matlab/%2Bdagnn/Split.m).

**Comment by LeeRock** [comment]
maybe you are not referencing the right matconv version.you need to git clone --recursive https://github.com/peiyunh/tiny.git

**Comment by niamul070** [comment]
Yes, I did git clone --recursive. Also, tried with some matconvnet versions as well.

**Comment by peiyunh** [comment]
You should find it at [matconvnet/matlab/+dagnn/Split.m](https://github.com/peiyunh/matconvnet/blob/d972fe848900c1c56d32e7a955ca38d8e05e0669/matlab/%2Bdagnn/Split.m)

**Comment by niamul070** [comment]
Yes, I am running that. I cloned it from your github.

**Comment by peiyunh** [comment]
Cool. Let me know if it works.

**Comment by johanna-codes** [comment]
I got the following warning:
opts.model
ans =
    'resnet-101-simple'
Unknown model: cannot initialize.

and then the following error:

Start using dagnn.DetLoss for loss
train: epoch 01:   1/1074:No appropriate method, property, or field 'forward' for class 'dagnn.DagNN'.

Error in cnn_train_dag_hardmine>process_epoch (line 286)
        net.forward(inputs, opts.derOutputs);

Error in cnn_train_dag_hardmine (line 148)
    [stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;

Error in cnn_widerface (line 214)
[net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...

Error in hr_res101 (line 48)
    cnn_widerface('inputSize', inputSize, ...

Please, help
