### ISSUE TITLE
Training hr_res101('train') error in class dagnn.DagNN

### ISSUE THREAD

**Issue by zhujiang123** [peiyunh/tiny#20]
Hello I am trying to train hr_res101('train') with Wider face data. After running the hr_res101('train') script I am getting the following error.

Start using dagnn.DetLoss for loss
cnn_train_dag_hardmine: resetting GPU
train: epoch 01:   1/1074:No appropriate method, property, or field forward for class dagnn.DagNN.

Error in cnn_train_dag_hardmine>process_epoch (line 286)
        net.forward(inputs, opts.derOutputs);

Error in cnn_train_dag_hardmine (line 148)
    [stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;

Error in cnn_widerface (line 212)
[net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...

Error in hr_res101 (line 41)
    cnn_widerface('inputSize', inputSize, ...

**Comment by peiyunh** [comment]
Did you run MatConvNet's tests to make sure you successfully installed the library?

**Comment by nurulj** [comment]
hi, apparently i encounter the same error. any idea how to solve it?

> Start using dagnn.DetLoss for loss
> cnn_train_dag_hardmine: resetting GPU
> train: epoch 01:   1/1074:No appropriate method, property, or field 'forward' for class 'dagnn.DagNN'.
> 
> Error in cnn_train_dag_hardmine>process_epoch (line 286)
>         net.forward(inputs, opts.derOutputs);
> 
> Error in cnn_train_dag_hardmine (line 148)
>     [stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;
> 
> Error in cnn_widerface (line 212)
> [net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...
> 
> Error in hr_res101 (line 41)
>     cnn_widerface('inputSize', inputSize, ...
