### ISSUE TITLE
Can I know what is the inference speed of your model? Can it be used real time?

### ISSUE THREAD

**Issue by yxchng** [peiyunh/tiny#23]
Ideally I am looking at inference speed of less than 50ms per image or 20fps.

**Comment by yxchng** [comment]
I tried downswmpling 4x before inference and it is still 500ms on 1080ti on the selfie photo. Is that a right number?

**Comment by peiyunh** [comment]
Generally, if you would like to speed things up, try tweaking the image pyramid scale(https://github.com/peiyunh/tiny/blob/master/tiny_face_detector.m#L107). 

For example, you could change that line to `scales = [-1, 0, 1]` for a (0.5x, 1x, 2x) image pyramid, which is much coarser than the one in the demo script. With such setting, the detector performs at around 1.4FPS on 1080p resolution and 3.1FPS on 720p resolution. 

If you don't care about finding faces that are extremely small, you could even go with `scales = [-1, 0]` or even `scales=[-1]`.

**Comment by yxchng** [comment]
Just wondering is 500ms also the speed you get? I definitely cannot get below 100ms unless I downsample 8x which gives bad accuracy
