### ISSUE TITLE
About Templates

### ISSUE THREAD

**Issue by ujjaldas1997** [peiyunh/tiny#26]
Hello @peiyunh  
    I read your paper regarding this work. But I didn't get the template extraction(
_We explore
multi-scale features extracted from the last layer of each
res-block, i.e. (res2cx, res3dx, res4fx, res5cx) in terms of
ResNet-50_ -- in your paper
). Which part of the [network](http://ethereon.github.io/netscope/#/gist/8a0d5ef37da9dc4cd611d178404b3641) contains template? Do you mean templates are nothing but the last layer of res2, res3, res4, res5? And what does cluster do(in the code net.meta.clusters) ?
And What is the significance of scale convolution in that above network?
Looking for your answer.

**Comment by peiyunh** [comment]
The templates are implemented with convolution filters. In the visualization you refer to, you can find `score_res3` and `score_res4` at the bottom. Such convolution is trained to output multi-channel detection heat maps. Each channel corresponds to one reference bounding box in `net.meta.clusters`.

**Comment by ujjaldas1997** [comment]
Thank you so much for your time @peiyunh . Actually I am new to matconvnet.
One more thing that bothering me is -- why did you used pre-trained model `pascal-fcn8s-tvg-dag.mat` and cluster values `RefBox_N25.mat` where as you can even train those by yourself?
What does `scale_conv` do in that network?
![photofacefun_com_1497028454](https://user-images.githubusercontent.com/22221731/26986499-6b82cbf0-4d65-11e7-9bef-0e9eb0d3d4ab.jpg)
I didn't get those above.

If you don't have time, I will be waiting.

**Comment by ujjaldas1997** [comment]
Hello @peiyunh 
I am really sorry to bother you.
But I am not able to understand the following : -
How did you train the [network](http://ethereon.github.io/netscope/#/gist/8a0d5ef37da9dc4cd611d178404b3641) with different image sizes(wider face) where as it is written as size to be [1 3 224 224], and the same is happening at the time of detection in `tiny_face_detector.m` as --
Initially
```
K>> net.vars(1, 1).value

ans =

     []
```
After loading image --
```
for s = 2.^scales
    img = imresize(raw_img, s, 'bilinear');
    img = bsxfun(@minus, img, averageImage);
    inputs = {'data', img};
    net.eval(inputs);
```
and sizes are to be --(iter1)
```
K>> net.vars(1, 1).value

ans =

     [64 64 3]
```
                                   (iter2)
```
K>> net.vars(1, 1).value

ans =

     [160 160 3]
```
And `net.eval(inputs)` assigns different boxes over faces(which I verify at the time of debugging). I really didn't understand this. My question may seem rediculous(and I am sorry for that), but tell me how is this happening? I am new to MatConvNet and I am trying to implement it in `Keras` -- python.
If you don't have time, I will be waiting for you.

**Comment by yu4u** [comment]
Hi @peiyunh, I have a similar question.
Referring to the visualized network, it seems that only res3 and res4 features are used for heatmap prediction.
Figure 4 in the paper indicates that res2-5 features are used for context. In the experiments, was a different network architecture used? I guess UNET-like network was used to deconv and concat different scale features...

**Comment by peiyunh** [comment]
@yu4u You are exactly right - the final model involves only res4+res3. Our experiment shows that res2+res3+res4 leads to almost identical performance comparing to res4+res3, while being more computationally expensive. So we chose to use only res4+res3 in our final model.

**Comment by peiyunh** [comment]
@ujjaldas1997 The pretrained model path is set in `scripts/hr_res101.m`, which will override the default setting in `cnn_widerface.m`.
