### ISSUE TITLE
未定义函数或变量 'nms_mex'。

### ISSUE THREAD

**Issue by wolfworld6** [peiyunh/tiny#29]
未定义函数或变量 'nms_mex'。

出错 nms (line 43)
    pick = nms_mex(double(boxes), double(overlap));

出错 tiny_face_detector (line 172)
ridx = nms(bboxes(:,[1:4 end]), nms_thresh);
I get the error，why？

**Comment by chinakook** [comment]
On windows, you should navigate to the nms path, and type mex nms_mex.cpp by yourself.

**Comment by zhangjinsong3** [comment]
I got the same problem!
I run the Demo in ubuntu well,but when I run it in windows,this problem occurred.
Did any on solve this problem?
