### ISSUE TITLE
Unable to read MAT-file /home/ysp/tiny/trained_models/hr_res101.mat: not a binary MAT-file.

### ISSUE THREAD

**Issue by special-yang** [peiyunh/tiny#36]

**Comment by special-yang** [comment]
sorry，I have poor English.
the mistakes when i run the code bboxes = tiny_face_detector('data/demo/selfie.jpg', './selfie.png', 0.5, 0.1, 0)

**Comment by zzw1123** [comment]
it is because you have not downloaded the file"hr_res101.mat"
you can download it from: https://www.cs.cmu.edu/~peiyunh/tiny/hr_res101.mat
and put it under the folder"trained_models"
then the error disappears.

**Comment by special-yang** [comment]
thank you very much ,the problem has been solved ,but when i run bboxes = tiny_face_detector('data/demo/selfie.jpg', './selfie.png', 0.5, 0.1, 0), we have meet some other problem :Undefined function or variable 'dagnn.Split'.

Error in dagnn.DagNN.loadobj (line 26)
    block = constr() ;

Error in tiny_face_detector (line 66)
net = dagnn.DagNN.loadobj(net.net);

**Comment by iFreilicht** [comment]
This issue has been solved, #42 discusses the new error.
