### ISSUE TITLE
problem :Undefined function or variable 'dagnn.Split'.

### ISSUE THREAD

**Issue by special-yang** [peiyunh/tiny#42]
when i run bboxes = tiny_face_detector('data/demo/selfie.jpg', './selfie.png', 0.5, 0.1, 0), we have meet some other problem :Undefined function or variable 'dagnn.Split'.

Error in dagnn.DagNN.loadobj (line 26)
block = constr() ;

Error in tiny_face_detector (line 66)
net = dagnn.DagNN.loadobj(net.net);

**Comment by iFreilicht** [comment]
Have you compiled and tested the MatConvNet submodule?

**Comment by ysp568** [comment]
I just run the code vl_compilenn.m

**Comment by special-yang** [comment]
I just run the code vl_compilenn.m。I don't know what other submodule  should be compile.

**Comment by iFreilicht** [comment]
Please also try

    >> vl_testnn('gpu', true);

**Comment by special-yang** [comment]
I have run the code Vl_testnn  and   this is the results
result =

  1x1683 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration

Totals:
   1683 Passed, 0 Failed, 0 Incomplete.
   403.6716 seconds testing time.

**Comment by iFreilicht** [comment]
That sounds like you installed the normal matconvnet. To use the code in this repository, you need to install @peiyunh's fork of matconvnet. You can check by navigating to the folder `matconvnet/matlab/+dagnn/` and checking if there is a file called `Split.m` in there.

If that file doesn't exist, that means you installed the normal version of matconvnet.

To resolve this, I would advise deleting this repository from your PC and re-cloning it recursively like so:

    git clone --recursive git@github.com:peiyunh/tiny.git

Then follow the [rest of the installation instructions](https://github.com/peiyunh/tiny#installation) step by step.

**Comment by special-yang** [comment]
@iFreilicht  Thank you very much ,and I will try it .

**Comment by special-yang** [comment]
I have solve the problem  thank you
