### ISSUE TITLE
hr_res101('train') error with ‘compute_dense_overlap.mexa64’

### ISSUE THREAD

**Issue by takecareofbigboss** [peiyunh/tiny#44]
i met this problem-------------------------------
Invalid MEX-file '/home/vis/dukang/tiny/utils/compute_dense_overlap.mexa64': dlopen: cannot load any more object with static TLS.

And in this link, https://github.com/peiyunh/tiny/issues/22, @niamul070  met the same problem. We have not solved it till now. Maybe it is helpful to know the version of your matlab. We both use matlab r2016b, so what is your version?

Hope you can reply to me asap.
Best Regards.

**Comment by peiyunh** [comment]
Closing this issue. See #22
