### ISSUE TITLE
segmentation fault when i use vl_imreadjpeg

### ISSUE THREAD

**Issue by takecareofbigboss** [peiyunh/tiny#45]
When i use this, all succeed.
vl_compilenn('enableImreadJpeg', true,'enableGpu', true,'enableGpu', true, 'cudaRoot', '/usr/local/cuda', 'enableCudnn', true,'cudaMethod', 'nvcc','ImageLibrary','libjpeg','imageLibraryCompileFlags', {'­-I/home/vis/.jumbo/include','-­L/home/vis/.jumbo/lib','-­ljpeg'},'cudnnRoot','/home/work/cudnn/cudnn_v5/cuda')

but when i use 
vl_test_imreadjpeg                                                                                                 
Segmentation fault

Hope you can help me to solve this problem

![image](https://user-images.githubusercontent.com/11883059/30063448-54103cda-9281-11e7-8160-9a08594cc409.png)

**Comment by peiyunh** [comment]
This seems an unrelated error to the detector. Please check if you have installed MatConvNet correctly.
