### ISSUE TITLE
Error in compile_mex (line 8). 

### ISSUE THREAD

**Issue by fsalmasri** [peiyunh/tiny#49]
I'm using matlab2017a, cuda 8 and cudnn5.1 for cuda 8. 
matconvnet compiled and tested without any fail. I just can't compile youe file. could you help please or tell me what configuration you used to compile it. 
thanks 

>> compile_mex
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
compute_dense_overlap.cc
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(48) : warning C4244: 'initializing' :
conversion from 'double' to 'const int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(49) : warning C4244: 'initializing' :
conversion from 'double' to 'const int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(51) : warning C4267: 'initializing' :
conversion from 'size_t' to 'const int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(57) : warning C4267: 'initializing' :
conversion from 'size_t' to 'const int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(70) : error C2664: 'mxArray
*mxCreateNumericArray_730(size_t,const size_t *,mxClassID,mxComplexity)' : cannot convert argument 2 from 'const int [4]' to
'const size_t *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(75) : warning C4244: 'initializing' :
conversion from 'const double' to 'const int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(76) : error C2664: 'mxArray
*mxCreateNumericArray_730(size_t,const size_t *,mxClassID,mxComplexity)' : cannot convert argument 2 from 'const int [3]' to
'const size_t *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(143) : warning C4244: 'initializing' :
conversion from 'const double' to 'int', possible loss of data
C:\Users\Administrator\Documents\MATLAB\Tiny2\tiny3\utils\compute_dense_overlap.cc(144) : warning C4244: 'initializing' :
conversion from 'const double' to 'int', possible loss of data

Error in compile_mex (line 8)
mex compute_dense_overlap.cc CXXOPTIMFLAGS='-O3 -DNDEBUG'

**Comment by fsalmasri** [comment]
solved after changing variable to t_size.

**Comment by AtenaKid** [comment]
Will you tell me which one to change  to t_size

**Comment by AtenaKid** [comment]
Any suggestion to fix the problem? 
Thank you
