### ISSUE TITLE
Error while train the model using 'hr_res101('train')

### ISSUE THREAD

**Issue by szk495732563** [peiyunh/tiny#50]
when i'm using the command 
>>'hr_res101('train')
an error occured like this:
'Unable to read file 'data/widerface/event_diffmap.mat': no such file or directory'
And i dont know where can i get this file. Can anyone solve it?

**Comment by takecareofbigboss** [comment]
actually, u dont need this file. What i own in the directory 'data/widerface' are:
imageStats.mat  imdb.mat  RefBox_N25.mat  RefBox_N25_scaled.mat  WIDER_test  WIDER_train  WIDER_val

**Comment by peiyunh** [comment]
Sorry for the confusion. @takecareofbigboss is right, you don't need that file. I've updated the code to remove those lines.
