### ISSUE TITLE
Train and out of memory  issue

### ISSUE THREAD

**Issue by aidandan** [peiyunh/tiny#51]
Hi, thanks for your work. 
When I use  `hr_res101('train')` , I had a bug,,
Error is below：
```
train: epoch 01:   1/1074:Error using gpuArray/max
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.
```

My notebook has GTX1050，ComputeCapability: '6.1'， TotalMemory: 4g.
Q:which parameter should I change？

**Comment by szk495732563** [comment]
I encountered this problem too, and i solved it by change the 'numSubBatches' option from 1 to 2.
i have 8 GPU memory, so i think u can change it to 4. U can also change the 'batchSize' option.
hope it helps.
