### ISSUE TITLE
Can someone please  tell me which versions of Matalb , Cuda and cudnn I have to use to test this project ?

### ISSUE THREAD

**Issue by vivekkumar1712** [peiyunh/tiny#53]

**Comment by takecareofbigboss** [comment]
Two options:
1.
ll /lib64/libc.*，you may need /lib64/libc.so.6 -> libc-2.17.so
which matlab，you may need /home/vis/softwares/Matlab2016b/bin/matlab
gcc -v，you may need gcc version 4.4.6
ll /usr/local, you may need cuda -> /home/work/cuda-8.0

2.
ll /lib64/libc.*，you may need /lib64/libc.so.6 -> libc-2.12.so
which matlab，you may need ~/liuwenxian/Code/Common/R2014a/bin/matlab
gcc -v，you may need  gcc version 4.4.6
ll /usr/local,you may need  cuda -> /home/work/cuda-7.5

**Comment by takecareofbigboss** [comment]
it works for me...
