### ISSUE TITLE
 hr_res101('eval') error

### ISSUE THREAD

**Issue by thenighthunter0** [peiyunh/tiny#54]
I have changed ignore_list to gt_list. 
but still meet error:
>> hr_res101('eval')
错误使用 fclose
文件标识符无效。使用 fopen 生成有效的文件标识符。

出错 cnn_widerface_eval (line 229)
    fclose(fout);

出错 hr_res101 (line 118)
      cnn_widerface_eval('clusterNum', clusterNum, ...

I am a beginer. maybe it is just a little issue.

**Comment by hhhzzj** [comment]
I have the same error too,let me know whether you solve it.Thank you so much!!@thenighthunter0
