### ISSUE TITLE
error with cluster in hr_res101('test')

### ISSUE THREAD

**Issue by guosusu** [peiyunh/tiny#57]
An error occurs when I try hr_res101('test'). It tells me that clusters(:,5) is unaccessible, for size(clusters)=[25,4]. Then, I check cluster_rects() and try to reproduce cluster, however, the size of new clusters is still 25*4. So, I just want to know how to get the 5th column of clusters, and the real mean of this column.Thank you!
@iFreilicht @peiyunh

**Comment by iFreilicht** [comment]
Please post the actual code you're running and show where the error exactly occurs and what the error message is.

Additionally, please refrain from @-mentioning me here. I have only contributed in the past and am currently not interested in providing support.

**Comment by guosusu** [comment]
My code is: hr_res101('test'), and the full stack trace is:

Evaluating model from models/widerface-resnet-101-simple-sample256-posfrac0.5-N25-bboxreg-cluster-scaled/net-epoch-48.mat
Error using cnn_widerface_test_AB (line 191)
Error detected on worker 3.
Attempted to access clusters(:,5); index out of bounds because size(clusters)=[25,4].

Error in hr_res101>(spmd body) (line 94)
        cnn_widerface_test_AB('overWrite', overWrite, ...

Error in hr_res101>(spmd) (line 89)
    spmd (taskPerGpu * gpuNum)

Error in hr_res101 (line 89)
    spmd (taskPerGpu * gpuNum)

Then, I check cnn_widerface_test_AB.m, finding out the error occurring as followed：

% canonical shapes 
clusters = net.meta.clusters;
clusters_h = clusters(:,4) - clusters(:,2) + 1;
clusters_w = clusters(:,3) - clusters(:,1) + 1;
clusters_scale = clusters(:,5);  %error occurring
max_cluster_h = max(clusters_h); 
max_cluster_w = max(clusters_w);

 The size of net.meta.clusters is 25*4, so it can not access the 5th column.
Then, I find out where I get my clusters, in cnn_widerface.m:

boxName = 'RefBox'; 
clusterPath = fullfile(opts.dataDir, clusterName(boxName,opts.clusterNum));

fprintf('cluster path: %s\n', clusterPath);

if ~exist(clusterPath)
  clusters = cluster_rects(imdb, opts.clusterNum, [minh minw], [maxh maxw]);
  save(clusterPath, 'clusters');
else
  load(clusterPath);
end
net.meta.clusters = clusters;

I try to reproduce my own clusters, but the size of new one is still 25*4. However, the model in your page, which is RefBox_N25_scaled.mat, is 25*5. So I want to know how to get the 5th column, and what this column means? By the way, I find anothe file in your page, which is RefBox_N25.mat. What differences are between the two files?
Thanks a lot! @iFreilicht @peiyunh

**Comment by guosusu** [comment]
It occurs to me that, when I produce my own imdb.mat, I find out that I can not get event.diff, because I don't have diff.map. I get my imbd.mat with diff absent. So, I want to know whether the diff effects the result, what does the diff mean, how can I get my own diff?
@iFreilicht @peiyunh

**Comment by peiyunh** [comment]
@guosusu 

For the question on "diff", please refer to #56. 

For the question on the 5th column of clusters, it means if we want to build a detector that detects faces of this canonical size, what scale should we build on upon. The way we pick scale is illustrated in Figure 8 of our paper (https://arxiv.org/pdf/1612.04402.pdf).
