### ISSUE TITLE
Error of Compiling Matconvnet

### ISSUE THREAD

**Issue by ngcthuong** [peiyunh/tiny#58]
Hello, 
I have compiled the original matconvnet in both GPU and CPU case. 
For this branch of matconvnet, I got this error. Any suggestion?

I use Window 10s, Matlab 2017a and Cuda 8.0. 

![image](https://user-images.githubusercontent.com/6524339/33523135-17adc6f6-d843-11e7-8b49-d1e548166df7.png)

**Comment by fengyuentau** [comment]
You need cudnn v5.1, see https://github.com/vlfeat/matconvnet/issues/1062#issuecomment-374163349
