### ISSUE TITLE
About resolution of templates

### ISSUE THREAD

**Issue by licheng1995** [peiyunh/tiny#66]
hello:
  I read your paper,and I'm confused that the difference about image resolution and templates resolution.You say finding (25x20) face,by building templates at 2x resolution.And you also say use a
“medium”-size template (50x40) to find small faces (25x20) on a 2X upsampled (interpolated) test image. I wonder  now that we can change the resolution of the image, why we change the resolution of templates?

**Comment by peiyunh** [comment]
To find faces with a pixel size of 25x20, we find it is better to build a template that responds to faces with a pixel size of 50x40. To use such a template to detect faces with a pixel size of 25x20, we can always use it on an image that is upsampled by 2 times. Does it make sense?

**Comment by licheng1995** [comment]
@peiyunh Always?your meaning is that we can also use t(25,20,2) on an image with original size? I find it your article writes that you use two type template  on an image that is upsampled by 2 times.And t(25,20,2) is a template that responds to faces with a pixel size of 50x40. Is t(50,40,1) is a template that responds to faces with a pixel size of 50x40? I'm confused their difference. Can you tell me the difference between using t(25,20,2) on an image that is upsampled by 2 times and using t(50,40,1) on an image that is upsampled by 2 times? Thank you
![20170325213904229](https://user-images.githubusercontent.com/18393376/36853667-0488e8f6-1daa-11e8-95a7-2ff7e36a7efa.jpg)

**Comment by peiyunh** [comment]
I feel section 4 of our paper, where we talk about the definition of a template, should directly answer your questions above.

**Comment by licheng1995** [comment]
Thank you
