### ISSUE TITLE
About undefined functions or variables ‘nms_mex’

### ISSUE THREAD

**Issue by loralyc** [peiyunh/tiny#67]
Hello,when i try to run the demo,it happens, and i can't find the file. how can i solve it?

**Comment by sahmed130** [comment]
bboxes = tiny_face_detector('data/demo/selfie.jpg', './selfie.png', 0.5, 0.1, 0)
Loading pretrained detector model...
Processing data/demo/selfie.jpg at scale 0.031250.
Processing data/demo/selfie.jpg at scale 0.062500.
Processing data/demo/selfie.jpg at scale 0.125000.
Processing data/demo/selfie.jpg at scale 0.250000.
Processing data/demo/selfie.jpg at scale 0.500000.
Processing data/demo/selfie.jpg at scale 1.000000.
Processing data/demo/selfie.jpg at scale 1.414214.
Processing data/demo/selfie.jpg at scale 2.000000.
Undefined function or variable 'nms_mex'.

Error in nms (line 43)
    pick = nms_mex(double(boxes), double(overlap));

Error in tiny_face_detector (line 172)
ridx = nms(bboxes(:,[1:4 end]), nms_thresh);

getting this error saying *Undefined function or variable 'nms_mex'.*
