### ISSUE TITLE
about the receptive fields calculated in your paper

### ISSUE THREAD

**Issue by caney1989** [peiyunh/tiny#69]
hello:
   I have read your paper carefully and I'm confused about the receptive fields corresponding to res-50 calculated in your paper. I have  calculated  it by myself, the results are 35, 99, 291, corresponding to res2, res3, res4, different from the results in your paper. Could you tell me the details about this calculation process??
Thank you !!

**Comment by peiyunh** [comment]
Matconvnet has a implementation for computing the receptive field sizes. You can refer to [matconvnet/matlab/+dagnn/@DagNN/getVarReceptiveFields.m](https://github.com/vlfeat/matconvnet/blob/master/matlab/%2Bdagnn/%40DagNN/getVarReceptiveFields.m)
