### ISSUE TITLE
what's the meaning of prob_cls and score_cls

### ISSUE THREAD

**Issue by liyuanyaun** [peiyunh/tiny#71]
in tiny_face_detector.m, there are three output in your model:score_reg,prob_cls and score_cls. score_reg is to refine the detection windows. and while prob_cls > prob_thresh, the detection could be keep. and score_cls is used for nms. but what's the meaning of prob_cls and score_cls? why not prob_cls  for nms? and  i find the value of score_cls  is more than 1. what is the score_cls represent? could anyone answer? thank you very much @peiyunh

**Comment by peiyunh** [comment]
`score_cls` is the raw score before normalization (sigmoid). `prob_cls` is probability score after normalization. Using either prob_cls or score_cls for NMS should not make a difference, because the relative order wasn't affected.
