### ISSUE TITLE
Documenting Batch Operations

### ISSUE THREAD

**Issue by varunagrawal** [peiyunh/tiny#73]
Hi Peiyun,
My query is regarding certain parts of `cnn_get_batch_hardmine.m` which is hard to understand and thus hard to port to other frameworks. 

In particular, I am not sure what is happening in the section from line 186-250. Similarly, the transformation from line 300-322 isn't well documented. It would be immensely helpful if you could elaborate on what is going on in those sections.

**Comment by peiyunh** [comment]
In case people are interested, Line 300 - 322 contains code that does crop and flip through index manipulation.

**Comment by varunagrawal** [comment]
@peiyunh after going through the code multiple times, I have realized that the lines 300-322 don't do anything except for flipping. The cropping doesn't happen because the input image is always 500x500 at that point.
