### ISSUE TITLE
Meaning of "templates" and how to get new "templates" in a newly trained network

### ISSUE THREAD

**Issue by liuwuliuyun** [peiyunh/tiny#74]
Hi, I two questions about the code and paper.

The first one is the term"templates" used in the paper. It seems to be some features extracted from a trained Resnet. But in which part of the code this extraction is implemented? 

The second one is that if I train a new network(e.g Mobilenets), how can I get the new "templates"?

Thanks for answering my questions.

**Comment by hhhzzj** [comment]
i have the same question，too

**Comment by luojiapeng14** [comment]
I have the same question too. It confuse me a few days. I read part of the code, it seems that the output 'score_cls' is a 25 depth matrix or tensor which corresponding to each 'templates'. I just don't understand the why?? If someone know it,  I'm very thanksful to you.

**Comment by kohenchia** [comment]
I'm guessing the author just means anchors, which is what the canonical term is for a predefined receptive area.

**Comment by peiyunh** [comment]
By template, I meant the predictor applied onto sliding window features.
