### ISSUE TITLE
How to train with my database?

### ISSUE THREAD

**Issue by nansbas** [peiyunh/tiny#75]
I want to train with my data, could you tell me where to start? Because I try to fine-tune it followed the readme and did‘t  get effective result.

Thank you for your answer very much.

**Comment by jian667** [comment]
If your task is also single class detection, you need to prepare the ground truth like wider face.

**Comment by peiyunh** [comment]
Not sure how helpful it would be, but #59 is related.

**Comment by pyupcgithub** [comment]
@jian667 do you know how to convert the text file with bounding box to the mat ?

**Comment by jian667** [comment]
@pyupcgithub Hi, if you mean ".mat" file, then you can use Matlab to convert.
