### ISSUE TITLE
How to pre-process the training data

### ISSUE THREAD

**Issue by ZhenyF** [peiyunh/tiny#76]
Hi @peiyunh 

I am just new to this and really interested to your paper.
I am wondering how do you pre-process the training data? (i.e. How do you generate the "heat-map"?)
I checked your MATLAB code called "[cnn_widerface](https://github.com/peiyunh/tiny/blob/master/cnn_widerface.m)" and there is a function ([@cnn_get_batch_logistic_zoom](https://github.com/peiyunh/tiny/blob/745a49cb38182a79f17d5090257914669d8e8089/cnn_widerface.m#L20)) for training data pre-processing. But I did not find it in your code. Could you please help me with that?

Many thanks!

**Comment by peiyunh** [comment]
Hi, please refer to https://github.com/peiyunh/tiny/blob/master/cnn_get_batch_hardmine.m for the batch getter function. The batch getter function is configured at run time in https://github.com/peiyunh/tiny/blob/master/scripts/hr_res101.m.
