### ISSUE TITLE
hr_res101('train') error: vl_argparse error

### ISSUE THREAD

**Issue by nurulj** [peiyunh/tiny#77]
**hello, just wanna ask. before I get to the vl_argparse error, i had this error first:**

> Start using dagnn.DetLoss for loss
> Parallel pool using the 'local' profile is shutting down.
> Starting parallel pool (parpool) using the 'local' profile ...
> connected to 4 workers.
> cnn_train_dag_hardmine: resetting GPU
> Error using cnn_train_dag_hardmine>prepareGPUs (line 616)
> Error detected on worker 3.
> 
> Error in cnn_train_dag_hardmine (line 132)
>   prepareGPUs(opts, epoch == start+1) ;
> 
> Error in cnn_widerface (line 212)
> [net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...
> 
> Error in hr_res101 (line 41)
>     cnn_widerface('inputSize', inputSize, ...
> 
> Caused by:
>     Error using gpuDevice (line 26)
>     Invalid CUDA device id: 3. Select a device id from the range 1:1.
 
**which then i realized it was because gpus variable line 21 in hr_res101.**
> gpus = [1 2 3 4];

**and i changed it to**
> gpus = [1];

**after the changes, i encounter this problem.** 

> Start using dagnn.DetLoss for loss
> cnn_train_dag_hardmine: resetting GPU
> train: epoch 01:   1/1074:Error using vl_argparse (line 63)
> OPTS must be a structure
> 
> Error in vl_argparse (line 160)
>         opts.(field) = vl_argparse(opts.(field), value, 'merge') ;
> 
> Error in vl_argparse (line 97)
>       opts = vl_argparse(opts, vertcat(params,values), varargin{:}) ;
> 
> Error in cnn_get_batch_hardmine (line 39)
> opts = vl_argparse(opts, varargin);
> 
> Error in cnn_widerface>getDagNNBatch (line 258)
> [images, clsmaps, regmaps] = batchGetter(imagePaths, imageSizes, labelRects, ...
> 
> Error in cnn_widerface>@(x,y)getDagNNBatch(batchGetter,bopts,useGpu,x,y) (line 243)
>     fn = @(x,y) getDagNNBatch(batchGetter, bopts,useGpu,x,y) ;
> 
> Error in cnn_train_dag_hardmine>process_epoch (line 268)
>     inputs = state.getBatch(state.imdb, batch) ;
> 
> Error in cnn_train_dag_hardmine (line 148)
>     [stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;
> 
> Error in cnn_widerface (line 212)
> [net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...
> 
> Error in hr_res101 (line 41)
>     cnn_widerface('inputSize', inputSize, ...

i have followed the the read.me in https://github.com/peiyunh/tiny. i ran the compile_mex and test_compute_dense_overlap, everything went well and i also can run the demo. i just encounter this problem when running hr_res101('train'). please help and correct me if i have done anything wrong.

**Comment by thenighthunter0** [comment]
how do you solve this issue?

**Comment by Gaurav1302** [comment]
@nurulj I am having the same problem, how did you solve the problem?
Thanks in advance!
