### ISSUE TITLE
Ask for training code ,and HR-VGG16

### ISSUE THREAD

**Issue by PearlDzzz** [peiyunh/tiny#8]
@peiyunh  Hi, peiyun, I have ran your offered demo, the face detection results are very good. Now I have some questions :
1. Can you share your model mentioned in the paper, e.g., HR-VGG16.
2. The detect time?  I try the HR-Res101 model, but it works very slowly.
3. How to train model on my own dataset. Can you share the training code?
Looking forward to your reply.

**Comment by peiyunh** [comment]
Hi @ChristineRYY :
1. I will add it shortly (likely this week). 
2. The runtime is dominated by the largest resolution the network processes. If there aren't many ultra-small faces in your application, you can try decreasing the test scale. 
3. I haven't found much time to clean up the training code. I will release it once I clean it up.

**Comment by PearlDzzz** [comment]
@peiyunh I use your latest updated code to train model on Wider Face, however, it encounter this question:

When I run: “ hr_res101('train'); ” in Matlab 2014b, GTX 745, Windows7 Professional, it reports an error:

Undefined function 'compute_dense_overlap' for input arguments of type 'double'.

Error cnn_get_batch_hardmine (line 378)
    iou = compute_dense_overlap(ofx,ofy,stx,sty,vsx,vsy,...

Error cnn_widerface>getDagNNBatch (line 258)
[images, clsmaps, regmaps] = batchGetter(imagePaths, imageSizes, labelRects, ...

Error cnn_widerface>@(x,y)getDagNNBatch(batchGetter,bopts,useGpu,x,y) (line 243)
    fn = @(x,y) getDagNNBatch(batchGetter, bopts,useGpu,x,y) ;

Error cnn_train_dag_hardmine>process_epoch (line 268)
    inputs = state.getBatch(state.imdb, batch) ;

Error cnn_train_dag_hardmine (line 148)
    [stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;

Error cnn_widerface (line 212)
[net, info] = trainFn(net, imdb, getBatchFn(batchGetter, opts, net.meta), ...

Error hr_res101 (line 41)
    cnn_widerface('inputSize', inputSize, ...

**Comment by peiyunh** [comment]
You may have to recompile the `utils/compute_dense_overlap.cc`. See 62f9a7fc7a4778c9fcbf1c25a5a7e277244a19ca for more details.
