### ISSUE TITLE
Question on train detector on my own dataset

### ISSUE THREAD

**Issue by WJ75090983** [peiyunh/tiny#82]
thank you very much,  I try to train using my own dataset, but i am confused about here,
![image](https://user-images.githubusercontent.com/31917641/49087826-ec652a00-f292-11e8-875f-f6d982d971b8.png)
 my dataset is images and XML (annotated result), I do not know how to convert my dataset to the mat file.
can anyone tell me? Very appreciate for your help.

**Comment by peiyunh** [comment]
If you have a different dataset, instead of loading `wider_face_train.mat`, you should read annotations from your dataset, and try to assign them to the member variables of imdb. The purpose is to create a structure called `imdb.mat` that includes image paths and object annotations.
