### ISSUE TITLE
Training on own data

### ISSUE THREAD

**Issue by HamzahNizami** [peiyunh/tiny#83]
@peiyunh Hi there im new to the whole computer vision scene and i was wondering if you or anyone else could help by releasing a step by step tutorial on how to train your model on other data sets. it would be very helpful. 

Thanks in advance

**Comment by peiyunh** [comment]
I had a very short answer here: https://github.com/peiyunh/tiny#how-do-i-train-it-on-my-own-datasets. 

I am definitely on board with the suggestion that a step-by-step tutorial would be awesome for beginners. Unfortunately, I don't have the bandwidth at this moment. If anyone decided to create such a tutorial, I'd be more than happy to add a link to that.
