### ISSUE TITLE
Initialise Resnet model

### ISSUE THREAD

**Issue by niubijo** [peiyunh/tiny#84]
Hi, I'm new to training a model and I'm trying to train a using a resnet but realise that there's no model for resnet in cnn_init. Can I get help with this? Thank you in advance

And I face problem to train with alexnet too. Is it because AlexNet is not using dagnn?

**Comment by peiyunh** [comment]
Sorry for the late response.  

You are right that there are no ResNets defined in cnn_init.m. Take a look at the script under `init/`. You will find a script that does some sort of network surgery based on a predefined ResNet structure. 

No, AlexNet was not implemented with DagNN though technically it can definitely be converted to a DagNN implementation.
