### ISSUE TITLE
Foveal descriptor

### ISSUE THREAD

**Issue by sabrinatuli** [peiyunh/tiny#85]
Hello peiyunh, thank you for an amazing paper. I want to know more about foveal descriptor in your paper. Also it would be helpful for me if you can indicate the foveal descriptor part in your code. Thanks

**Comment by peiyunh** [comment]
The foveal descriptor is implemented by making predictions based on features from different layers, much like what has been described in this paper: https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf. It is also often referred to as hypercolumn features: http://home.bharathh.info/pubs/pdfs/BharathCVPR2015.pdf. They both describe a trick that allows us to compute the results of running linear predictors on the foveal descriptors without explicitly constructing the foveal descriptors. While being much more efficient in terms of speed and memory, such results are mathematically equivalent to what we would've gotten if we were to construct the foveal descriptors explicitly and run linear predictors. 

Hopefully this explanation above is helpful for you and anyone else who is having the same question. :-)
