### ISSUE TITLE
I have the same question too. It confuse me a few days. I read part of the code, it seems that the output 'score_cls' is a 25 depth matrix or tensor which corresponding to each 'templates'. I just don't understand the why?? If someone know it,  I'm very thanksful to you.

### ISSUE THREAD

**Issue by JeremyLinky** [peiyunh/tiny#87]
I have the same question too. It confuse me a few days. I read part of the code, it seems that the output 'score_cls' is a 25 depth matrix or tensor which corresponding to each 'templates'. I just don't understand the why?? If someone know it,  I'm very thanksful to you.

_Originally posted by @woolpeeker in https://github.com/peiyunh/tiny/issues/74#issuecomment-401340270_

**Comment by JeremyLinky** [comment]
Can anyone tell me that why output 'score_cls' is a 25 depth matrix or tensor which corresponding to each 'templates', so as to score_reg and prob_cls. How the code do that???

**Comment by peiyunh** [comment]
Sorry for my delayed reply. 25 is the number of anchors. Does that make sense to you?
