### ISSUE TITLE
hr_res101.mat broken link

### ISSUE THREAD

**Issue by panchgonzalez** [peiyunh/tiny#88]
Hi @peiyunh,

It looks like the link to the pretrained ResNet101 weights is broken 

https://www.cs.cmu.edu/~peiyunh/tiny/hr_res101.mat

I get an ` 404: Not Found` error

```bash
(base) ➜  ~ wget https://www.cs.cmu.edu/%7Epeiyunh/tiny/hr_res101.mat              
--2020-04-23 10:53:25--  https://www.cs.cmu.edu/%7Epeiyunh/tiny/hr_res101.mat
Resolving www.cs.cmu.edu (www.cs.cmu.edu)... 128.2.42.95
Connecting to www.cs.cmu.edu (www.cs.cmu.edu)|128.2.42.95|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-23 10:53:25 ERROR 404: Not Found.
```

**Comment by peiyunh** [comment]
Hi @panchgonzalez 

I moved it to my google drive. You can download it here: https://drive.google.com/file/d/1YO8zTXGCACRZvHDxtW8dEZL7CE8HVFJ8/view?usp=sharing

**Comment by panchgonzalez** [comment]
Great, thanks for the quick reply @peiyunh!
