### ISSUE TITLE
Would please release the training code?

### ISSUE THREAD

**Issue by MaxLingwei** [peiyunh/tiny#9]
Dear peiyunh, 
I've used your demo and got a really excellent result. Now I want to train a model in my own dataset. So would release the training code please? Thank you very much!

**Comment by peiyunh** [comment]
Hi @MaxLingwei , 

Thanks for your comment. I haven't found much time to clean up the training code. I will release it once I get it done.

**Comment by MaxLingwei** [comment]
Thank you very much.
By the way, have you trained a caffe model with your network? Or do you think it's possible to convert a matconvnet .mat model to the Caffe model? Because our project need to use caffe and implement in c++

**Comment by peiyunh** [comment]
Training code is out. I'm closing this issue.
